version: "3.8"
networks:
  influxdb:
  telegraf:

services:
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - influxdb
    user: "${INFLUX_UID}:${INFLUX_GID}"

  telegraf:
    image: telegraf
    environment:
      - HOST_HOSTNAME=${TELEGRAF_HOSTNAME}
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
    volumes:
      - /:/hostfs:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - influxdb
      - telegraf
    user: "${TELEGRAF_UID}:${TELEGRAF_GID}"
    depends_on:
      - influxdb

  speedtest:
    build:
      context: ./speedtest
      dockerfile: speedtest.Dockerfile
    networks:
      - telegraf
    depends_on:
      - telegraf

  grafana:
    image: grafana/grafana
    environment:
      - GF_DISABLE_INITIAL_ADMIN_CREATION=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana123
      - GF_DATE_FORMATS_INTERVAL_DAY='DD/MM'
      - GF_DATE_FORMATS_INTERVAL_HOUR='DD/MM HH:mm'
    volumes:
      - /var/lib/grafana/:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - influxdb
    user: "${GRAFANA_UID}:${GRAFANA_GID}"
    depends_on:
      - influxdb
      - telegraf
