version: "3.8"
networks:
  influxdb:
      name: influxdb
  influxdb2:
      name: influxdb2
  telegraf:
      name: telegraf
  traefik:
      name: traefik

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=influx_admin
      - INFLUXDB_ADMIN_PASSWORD=influx_admin123
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - influxdb
    user: "${INFLUX_UID}:${INFLUX_GID}"
    restart: unless-stopped

  influxdb2:
    image: influxdb:2.0
    container_name: influxdb2
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    ports:
      - "9086:8086"
    networks:
      - influxdb2
    user: "${INFLUX_UID}:${INFLUX_GID}"
    restart: unless-stopped

  telegraf:
    image: telegraf
    container_name: telegraf
    environment:
      - HOST_HOSTNAME=${TELEGRAF_HOSTNAME}
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
    volumes:
      - /:/hostfs:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - influxdb
      - telegraf
    user: "${TELEGRAF_UID}:${TELEGRAF_GID}"
    depends_on:
      - influxdb
    restart: unless-stopped

  speedtest:
    build:
      context: ./speedtest
      dockerfile: speedtest.Dockerfile
    container_name: speedtest
    networks:
      - telegraf
    depends_on:
      - telegraf
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_DISABLE_INITIAL_ADMIN_CREATION=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana123
      - GF_DATE_FORMATS_INTERVAL_DAY='DD/MM'
      - GF_DATE_FORMATS_INTERVAL_HOUR='DD/MM HH:mm'
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
    user: "995:995"
    volumes:
      - ./grafana/data/var/lib/grafana:/var/lib/grafana
      - ./home_sensor/rest_server/data/:/rest_server_data:ro
    ports:
      - "3000:3000"
    networks:
      - influxdb
      - traefik
    depends_on:
      - influxdb
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.middlewares=grafana-stripprefix"
      - "traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes=/grafana"
      - "traefik.docker.network=traefik"
    restart: unless-stopped

  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=Europe/Amsterdam
      - SUBDOMAINS=pedvide
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped

  traefik:
    image: "traefik"
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "51820:51820/udp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/config.toml:/etc/traefik/traefik.toml:ro"
      - "./log/traefik:/var/log"
    networks:
      - traefik
      - influxdb
    restart: unless-stopped

  logrotate:
    build:
      context: ./logrotate
      dockerfile: Dockerfile
    container_name: logrotate
    environment:
      - LOGROTATE_FILE_PATTERN="*.log"
      # don't rotate at all but truncate logs when they exceed the configured rotation size
      - LOGROTATE_ROTATE="0"
      - LOGROTATE_SIZE="50M"
      - LOGROTATE_CRON="hourly"
    volumes:
      - ./log:/log
    restart: unless-stopped

  ntp:
    build:
      context: ./ntp
      dockerfile: Dockerfile
    container_name: ntp
    volumes:
        - ./ntp/chrony.conf:/etc/chrony/chrony.conf:ro
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    ports:
      - "123:123/udp"
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "./fail2ban/data:/data"
      - "./log:/var/log/containers:ro"
      - "/var/log:/var/log/host:ro"
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped

  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - SERVERURL=pedvide.duckdns.org
      - PEERS=surface-tablet,smartphone #optional
      - PEERDNS=192.168.2.254 #optional
      - ALLOWEDIPS=192.168.2.0/24 #optional
    networks:
      - traefik
    volumes:
      - ./wireguard/data:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.udp.routers.wireguard-udp.entrypoints=wireguard"
      - "traefik.udp.routers.wireguard-udp.service=wireguard-udp-svc"
      - "traefik.udp.services.wireguard-udp-svc.loadbalancer.server.port=51820"
    restart: unless-stopped

