version: "3.8"
networks:
  influxdb:
   
services:
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks: 
      - influxdb
    user: "${INFLUX_UID}:${INFLUX_GID}"
