version: "3.8"
networks:
  influxdb:
   
services:
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks: 
      - influxdb
    user: "${INFLUX_UID}:${INFLUX_GID}"

  telegraf:
    build:
      context: ./telegraf/telegraf-monitoring 
      dockerfile: telegraf-monitoring.Dockerfile
    environment:
      - HOST_HOSTNAME=${TELEGRAF_HOSTNAME}
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc  
      - HOST_SYS=/hostfs/sys 
      - HOST_VAR=/hostfs/var 
    volumes:
      - /:/hostfs:ro 
      - ./telegraf/telegraf-monitoring/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - influxdb
    user: "${TELEGRAF_UID}:${TELEGRAF_GID}"
    depends_on:
      - influxdb
