[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level = "INFO"

[accessLog]
  filePath = "/var/log/access.log"

[entryPoints] # Creating an entrypoint listening on port 80 with the default protocol of TCP
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.wireguard]
    address = ":51820/udp"

[api]
  insecure = true # Enables the web UI

[providers]
  [providers.docker]
    exposedByDefault = false

  [providers.file]
    directory = "/certificates"

[metrics]
  [metrics.influxDB]
    address = "http://influxdb:8086"
    #address = "http://telegraf:8081"
    protocol = "http"
    database = "traefik"
    retentionPolicy = "weekly"
    username = "traefik"
    password = "traefik123"

